# Generated by Django 4.0.6 on 2022-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='teste', max_length=50),
            preserve_default=False,
        ),
    ]
